# Generated by Django 4.2.6 on 2023-11-11 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='topic',
            field=models.TextField(choices=[('ADS', 'Ads'), ('LIVE', 'Live'), ('LEVEL', 'Level'), ('REWARD', 'Reward'), ('STREAK', 'Streak'), ('COMMENT', 'Comment'), ('GENERAL', 'General')]),
        ),
    ]
