# Generated by Django 4.2.3 on 2023-07-25 03:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profile_daily_streak_minutes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='daily_streak_minutes',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(240)]),
        ),
    ]
