# Generated by Django 4.2.5 on 2023-10-01 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_notification_icon_alter_notification_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='topic',
            field=models.TextField(choices=[('ADS', 'ads'), ('REWARDS', 'REWARDS'), ('COMMENTS', 'comments')]),
        ),
    ]
