# Generated by Django 4.2.5 on 2023-10-01 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_notification_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='image',
            field=models.URLField(default='REWARD'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notification',
            name='topic',
            field=models.TextField(choices=[('ADS', 'Ads'), ('REWARD', 'Reward'), ('STREAK', 'Streak'), ('COMMENT', 'Comment')]),
        ),
    ]
