# Generated by Django 4.2.6 on 2023-12-04 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.TextField(choices=[('OTHER', 'Other'), ('MALE', 'Male'), ('FEMALE', 'Female')], default='OTHER'),
            preserve_default=False,
        ),
    ]
