# Generated by Django 4.2.5 on 2023-09-12 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_settings_options_notification_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='assets/users/avatars/'),
        ),
    ]
