# Generated by Django 4.2.5 on 2023-10-04 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_notification_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='topic',
            field=models.TextField(choices=[('ADS', 'Ads'), ('LIVE', 'LIVE'), ('LEVEL', 'Level'), ('REWARD', 'Reward'), ('STREAK', 'Streak'), ('COMMENT', 'Comment'), ('GENERAL', 'General')]),
        ),
    ]
