# Generated by Django 4.2.5 on 2023-10-07 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_notification_topic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ('-created_at', '-updated_at')},
        ),
    ]
