# Generated by Django 4.2.5 on 2023-10-07 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_notification_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='streaks',
        ),
    ]
