# Generated by Django 4.1 on 2023-08-05 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enhancement', '0002_enhancement_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='enhancement',
            name='type',
            field=models.TextField(choices=[('ENHANCE', 'Enhance'), ('SUMMARIZE', 'Summaize')], default='ENHANCE'),
            preserve_default=False,
        ),
    ]
