[tool.poetry]
name = "beelearn"
version = "0.1.0"
description = ""
authors = ["Oguntunde Caleb Fiyinfoluwa <oasis.mystre@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"
Django = "^4.2.3"
djangorestframework = "^3.14.0"
Pillow = "^10.0.0"
dj-url-filter = "^0.4.4"
six = "^1.16.0"
django-cors-headers = "^4.2.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
