services:
  - type: web
    name: beelearn
    runtime: python
    repo: https://github.com/oasisMystre/beelearn_api
    plan: free
    buildCommand: "./build.sh"
    startCommand: "daphne beelearn.asgi:application --bind 0.0.0.0 -v2"
    domains:
      - v1.api.usebeelearn.com
      - beelearn.onrender.com
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: PYTHON_VERSION
        value: 3.11.4
      - key: RENDER_EXTERNAL_HOSTNAME
        value: v1.api.usebeelearn.com,beelearn.onrender.com
    envVarGroups:
      - name: BeeLearn 
