services:
  - type: web
    name: beelearn
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "daphne -b 0.0.0.0 beelearn.asgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: PYTHON_VERSION
        value: 3.11.4
