# Generated by Django 4.2.5 on 2023-09-12 22:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import martor.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('is_answer', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ReorderChoice',
            fields=[
                ('choice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assessment.choice')),
                ('position', models.PositiveIntegerField()),
            ],
            bases=('assessment.choice',),
        ),
        migrations.CreateModel(
            name='TextOptionQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', martor.models.MartorField()),
                ('question', models.TextField()),
                ('type', models.TextField(choices=[('TEXT', 'Text'), ('DRAG_DROP', 'Drag Drop'), ('TEXT_OPTION', 'Text Option'), ('SINGLE_CHOICE', 'Multiple Choice'), ('MULTIPLE_CHOICE', 'Multiple Choice'), ('RE_ORDER_CHOICE', 'Reorder Choice')], default='TEXT_OPTION', editable=False)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_option_question_creator', to=settings.AUTH_USER_MODEL)),
                ('editors', models.ManyToManyField(blank=True, related_name='text_option_question_editors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SingleChoiceQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', martor.models.MartorField()),
                ('type', models.TextField(choices=[('TEXT', 'Text'), ('DRAG_DROP', 'Drag Drop'), ('TEXT_OPTION', 'Text Option'), ('SINGLE_CHOICE', 'Multiple Choice'), ('MULTIPLE_CHOICE', 'Multiple Choice'), ('RE_ORDER_CHOICE', 'Reorder Choice')], default='SINGLE_CHOICE', editable=False)),
                ('choices', models.ManyToManyField(to='assessment.choice')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='single_choice_question_creator', to=settings.AUTH_USER_MODEL)),
                ('editors', models.ManyToManyField(blank=True, related_name='single_choice_question_editors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MultiChoiceQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', martor.models.MartorField()),
                ('type', models.TextField(choices=[('TEXT', 'Text'), ('DRAG_DROP', 'Drag Drop'), ('TEXT_OPTION', 'Text Option'), ('SINGLE_CHOICE', 'Multiple Choice'), ('MULTIPLE_CHOICE', 'Multiple Choice'), ('RE_ORDER_CHOICE', 'Reorder Choice')], default='MULTIPLE_CHOICE', editable=False)),
                ('choices', models.ManyToManyField(to='assessment.choice')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multi_choice_question_creator', to=settings.AUTH_USER_MODEL)),
                ('editors', models.ManyToManyField(blank=True, related_name='multi_choice_question_editors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DragDropQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', martor.models.MartorField()),
                ('question', martor.models.MartorField()),
                ('choices', models.TextField()),
                ('type', models.TextField(choices=[('TEXT', 'Text'), ('DRAG_DROP', 'Drag Drop'), ('TEXT_OPTION', 'Text Option'), ('SINGLE_CHOICE', 'Multiple Choice'), ('MULTIPLE_CHOICE', 'Multiple Choice'), ('RE_ORDER_CHOICE', 'Reorder Choice')], default='DRAG_DROP', editable=False)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drag_drop_question_creator', to=settings.AUTH_USER_MODEL)),
                ('editors', models.ManyToManyField(blank=True, related_name='drag_drop_question_editors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReorderQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', martor.models.MartorField()),
                ('type', models.TextField(choices=[('TEXT', 'Text'), ('DRAG_DROP', 'Drag Drop'), ('TEXT_OPTION', 'Text Option'), ('SINGLE_CHOICE', 'Multiple Choice'), ('MULTIPLE_CHOICE', 'Multiple Choice'), ('RE_ORDER_CHOICE', 'Reorder Choice')], default='RE_ORDER_CHOICE', editable=False)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reorder_question_creator', to=settings.AUTH_USER_MODEL)),
                ('editors', models.ManyToManyField(blank=True, related_name='reorder_question_editors', to=settings.AUTH_USER_MODEL)),
                ('choices', models.ManyToManyField(to='assessment.reorderchoice')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
