# Generated by Django 4.1 on 2023-08-28 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('is_answer', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DragDropQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('question', models.TextField()),
                ('type', models.TextField(choices=[('TEXT', 'Text'), ('DRAG_DROP', 'Drag Drop'), ('TEXT_OPTION', 'Text Option'), ('SINGLE_CHOICE', 'Multiple Choice'), ('MULTIPLE_CHOICE', 'Multiple Choice')], default='DRAG_DROP', editable=False, max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TextOptionQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('question', models.TextField()),
                ('type', models.TextField(choices=[('TEXT', 'Text'), ('DRAG_DROP', 'Drag Drop'), ('TEXT_OPTION', 'Text Option'), ('SINGLE_CHOICE', 'Multiple Choice'), ('MULTIPLE_CHOICE', 'Multiple Choice')], default='TEXT_OPTION', editable=False, max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SingleChoiceQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('type', models.TextField(choices=[('TEXT', 'Text'), ('DRAG_DROP', 'Drag Drop'), ('TEXT_OPTION', 'Text Option'), ('SINGLE_CHOICE', 'Multiple Choice'), ('MULTIPLE_CHOICE', 'Multiple Choice')], default='SINGLE_CHOICE', editable=False, max_length=128)),
                ('choices', models.ManyToManyField(to='assessment.choice')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MultiChoiceQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('type', models.TextField(choices=[('TEXT', 'Text'), ('DRAG_DROP', 'Drag Drop'), ('TEXT_OPTION', 'Text Option'), ('SINGLE_CHOICE', 'Multiple Choice'), ('MULTIPLE_CHOICE', 'Multiple Choice')], default='MULTIPLE_CHOICE', editable=False, max_length=128)),
                ('choices', models.ManyToManyField(to='assessment.choice')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
