# Generated by Django 4.2.6 on 2023-11-06 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reorderchoicequestion',
            name='choices',
            field=models.ManyToManyField(to='assessment.reorderoption'),
        ),
    ]
