# Generated by Django 4.1 on 2023-09-11 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assessment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReorderChoice',
            fields=[
                ('choice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assessment.choice')),
                ('position', models.PositiveIntegerField()),
            ],
            bases=('assessment.choice',),
        ),
        migrations.AlterField(
            model_name='dragdropquestion',
            name='question',
            field=martor.models.MartorField(),
        ),
        migrations.AlterField(
            model_name='dragdropquestion',
            name='title',
            field=martor.models.MartorField(),
        ),
        migrations.AlterField(
            model_name='multichoicequestion',
            name='title',
            field=martor.models.MartorField(),
        ),
        migrations.AlterField(
            model_name='singlechoicequestion',
            name='title',
            field=martor.models.MartorField(),
        ),
        migrations.AlterField(
            model_name='textoptionquestion',
            name='title',
            field=martor.models.MartorField(),
        ),
        migrations.CreateModel(
            name='ReorderQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', martor.models.MartorField()),
                ('type', models.TextField(choices=[('TEXT', 'Text'), ('DRAG_DROP', 'Drag Drop'), ('TEXT_OPTION', 'Text Option'), ('SINGLE_CHOICE', 'Multiple Choice'), ('MULTIPLE_CHOICE', 'Multiple Choice')], max_length=128)),
                ('choices', models.ManyToManyField(to='assessment.reorderchoice')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reorder_question_creator', to=settings.AUTH_USER_MODEL)),
                ('editors', models.ManyToManyField(blank=True, related_name='reorder_question_editors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
