# Generated by Django 4.1 on 2023-09-11 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_reorderchoice_alter_dragdropquestion_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dragdropquestion',
            name='type',
            field=models.TextField(choices=[('TEXT', 'Text'), ('DRAG_DROP', 'Drag Drop'), ('TEXT_OPTION', 'Text Option'), ('SINGLE_CHOICE', 'Multiple Choice'), ('MULTIPLE_CHOICE', 'Multiple Choice'), ('RE_ORDER_CHOICE', 'Reorder Choice')], default='DRAG_DROP', editable=False),
        ),
        migrations.AlterField(
            model_name='multichoicequestion',
            name='type',
            field=models.TextField(choices=[('TEXT', 'Text'), ('DRAG_DROP', 'Drag Drop'), ('TEXT_OPTION', 'Text Option'), ('SINGLE_CHOICE', 'Multiple Choice'), ('MULTIPLE_CHOICE', 'Multiple Choice'), ('RE_ORDER_CHOICE', 'Reorder Choice')], default='MULTIPLE_CHOICE', editable=False),
        ),
        migrations.AlterField(
            model_name='reorderquestion',
            name='type',
            field=models.TextField(choices=[('TEXT', 'Text'), ('DRAG_DROP', 'Drag Drop'), ('TEXT_OPTION', 'Text Option'), ('SINGLE_CHOICE', 'Multiple Choice'), ('MULTIPLE_CHOICE', 'Multiple Choice'), ('RE_ORDER_CHOICE', 'Reorder Choice')], default='RE_ORDER_CHOICE', editable=False),
        ),
        migrations.AlterField(
            model_name='singlechoicequestion',
            name='type',
            field=models.TextField(choices=[('TEXT', 'Text'), ('DRAG_DROP', 'Drag Drop'), ('TEXT_OPTION', 'Text Option'), ('SINGLE_CHOICE', 'Multiple Choice'), ('MULTIPLE_CHOICE', 'Multiple Choice'), ('RE_ORDER_CHOICE', 'Reorder Choice')], default='SINGLE_CHOICE', editable=False),
        ),
        migrations.AlterField(
            model_name='textoptionquestion',
            name='type',
            field=models.TextField(choices=[('TEXT', 'Text'), ('DRAG_DROP', 'Drag Drop'), ('TEXT_OPTION', 'Text Option'), ('SINGLE_CHOICE', 'Multiple Choice'), ('MULTIPLE_CHOICE', 'Multiple Choice'), ('RE_ORDER_CHOICE', 'Reorder Choice')], default='TEXT_OPTION', editable=False),
        ),
    ]
