# Generated by Django 4.2.5 on 2023-09-24 12:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assessment', '0002_alter_dragdropquestion_type_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReorderQuestion',
            new_name='ReorderChoiceQuestion',
        ),
    ]
