# Generated by Django 4.2.6 on 2023-11-11 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_alter_reorderchoicequestion_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dragdropquestion',
            name='type',
            field=models.TextField(choices=[('TEXT', 'Text'), ('DRAG_DROP', 'Drag Drop'), ('TEXT_OPTION', 'Text Option'), ('SINGLE_CHOICE', 'Single Choice'), ('MULTIPLE_CHOICE', 'Multiple Choice'), ('REORDER_CHOICE', 'Reorder Choice')], default='DRAG_DROP', editable=False),
        ),
        migrations.AlterField(
            model_name='multichoicequestion',
            name='type',
            field=models.TextField(choices=[('TEXT', 'Text'), ('DRAG_DROP', 'Drag Drop'), ('TEXT_OPTION', 'Text Option'), ('SINGLE_CHOICE', 'Single Choice'), ('MULTIPLE_CHOICE', 'Multiple Choice'), ('REORDER_CHOICE', 'Reorder Choice')], default='MULTIPLE_CHOICE', editable=False),
        ),
        migrations.AlterField(
            model_name='reorderchoicequestion',
            name='type',
            field=models.TextField(choices=[('TEXT', 'Text'), ('DRAG_DROP', 'Drag Drop'), ('TEXT_OPTION', 'Text Option'), ('SINGLE_CHOICE', 'Single Choice'), ('MULTIPLE_CHOICE', 'Multiple Choice'), ('REORDER_CHOICE', 'Reorder Choice')], default='REORDER_CHOICE', editable=False),
        ),
        migrations.AlterField(
            model_name='singlechoicequestion',
            name='type',
            field=models.TextField(choices=[('TEXT', 'Text'), ('DRAG_DROP', 'Drag Drop'), ('TEXT_OPTION', 'Text Option'), ('SINGLE_CHOICE', 'Single Choice'), ('MULTIPLE_CHOICE', 'Multiple Choice'), ('REORDER_CHOICE', 'Reorder Choice')], default='SINGLE_CHOICE', editable=False),
        ),
        migrations.AlterField(
            model_name='textoptionquestion',
            name='type',
            field=models.TextField(choices=[('TEXT', 'Text'), ('DRAG_DROP', 'Drag Drop'), ('TEXT_OPTION', 'Text Option'), ('SINGLE_CHOICE', 'Single Choice'), ('MULTIPLE_CHOICE', 'Multiple Choice'), ('REORDER_CHOICE', 'Reorder Choice')], default='TEXT_OPTION', editable=False),
        ),
    ]
