# Generated by Django 4.2.6 on 2023-11-13 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0003_alter_dragdropquestion_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='dragdropquestion',
            name='choices',
        ),
        migrations.AddField(
            model_name='dragdropquestion',
            name='choices',
            field=models.ManyToManyField(to='assessment.choice'),
        ),
    ]
