# Generated by Django 4.2.5 on 2023-09-18 17:40

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('skid', models.CharField(blank=True, max_length=32, null=True)),
                ('name', models.CharField(max_length=128)),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('description', models.TextField(blank=True, null=True)),
                ('period', models.TextField(choices=[('YEARLY', 'Yearly'), ('MONTHLY', 'Monthly'), ('LIFETIME', 'LifeTime'), ('QUARTERLY', 'Quarterly')])),
                ('flutterwave_plan_id', models.TextField(blank=True, null=True)),
                ('is_premium', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reference', models.TextField(blank=True, null=True)),
                ('status', models.TextField(choices=[('FAILED', 'FAILED'), ('PENDING', 'PENDING'), ('SUCCESSFUL', 'SUCCESSFUL')], default='PENDING')),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
