# Generated by Django 4.2.6 on 2023-10-21 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField()),
                ('price', models.TextField()),
                ('amount', models.TextField()),
                ('currency', models.TextField()),
                ('description', models.TextField()),
                ('flutterwave_plan_id', models.TextField(blank=True, null=True)),
                ('paystack_plan_code', models.TextField(blank=True, null=True)),
                ('consumable', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order_id', models.TextField(blank=True, null=True)),
                ('web_order_id', models.TextField(blank=True, null=True)),
                ('token', models.TextField(blank=True, null=True)),
                ('status', models.TextField(choices=[('FAILED', 'Failed'), ('PENDING', 'Pending'), ('UNKNOWN', 'Unknown'), ('CANCELED', 'Canceled'), ('SUCCESSFUL', 'Successful')], default='UNKNOWN')),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
