# Generated by Django 4.2.5 on 2023-09-26 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='skid',
            new_name='sku_id',
        ),
    ]
