# Generated by Django 4.2.5 on 2023-09-28 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_remove_product_description_remove_product_is_premium_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='amount',
            field=models.TextField(default=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='currency',
            field=models.TextField(default='NGN'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.TextField(default='Beelearn premium membership'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.TextField(default='₦1000'),
            preserve_default=False,
        ),
    ]
