# Generated by Django 4.2.5 on 2023-09-29 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_product_amount_product_currency_product_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.TextField(choices=[('FAILED', 'Failed'), ('PENDING', 'Pending'), ('UNKNOWN', 'Unknown'), ('CANCELED', 'Canceled'), ('SUCCESSFUL', 'Successful')], default='PENDING'),
        ),
    ]
