# Generated by Django 4.2.5 on 2023-09-29 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_alter_purchase_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='reference',
            new_name='token',
        ),
        migrations.AlterField(
            model_name='purchase',
            name='id',
            field=models.TextField(primary_key=True, serialize=False, unique=True),
        ),
    ]
