# Generated by Django 4.2.5 on 2023-09-29 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_rename_reference_purchase_token_alter_purchase_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sku_id',
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.CharField(max_length=32, primary_key=True, serialize=False, unique=True),
        ),
    ]
