# Generated by Django 4.2.5 on 2023-10-07 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_remove_product_sku_id_alter_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='flutterwave_plan_id',
            new_name='paystack_plan_code',
        ),
    ]
