# Generated by Django 4.2.5 on 2023-10-07 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_rename_flutterwave_plan_id_product_paystack_plan_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='fluttewave_plan_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
