# Generated by Django 4.2.5 on 2023-10-07 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0010_product_fluttewave_plan_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='fluttewave_plan_id',
            new_name='flutterwave_plan_id',
        ),
    ]
