# Generated by Django 4.2.5 on 2023-10-07 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0012_purchase_order_id_alter_purchase_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='web_order_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='order_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
