# Generated by Django 4.2.6 on 2023-11-30 19:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reward', '0002_alter_price_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('type', models.TextField(choices=[('MARS', 'Mars'), ('VENUS', 'Venus'), ('EARTH', 'Earth'), ('SATURN', 'Saturn'), ('MERCURY', 'Mercury'), ('JUPITER', 'Jupiter')], unique=True)),
                ('icon', models.ImageField(upload_to='leagues/icons')),
                ('price', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reward.price')),
            ],
        ),
        migrations.CreateModel(
            name='UserLeague',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, default=django.utils.timezone.now)),
                ('xp', models.IntegerField(default=0)),
                ('xp_before', models.IntegerField(default=0)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_leagues', to='leaderboard.league')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-xp_before'],
            },
        ),
        migrations.AddField(
            model_name='league',
            name='users',
            field=models.ManyToManyField(blank=True, through='leaderboard.UserLeague', to=settings.AUTH_USER_MODEL),
        ),
    ]
