# Generated by Django 4.2.6 on 2023-11-30 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='color',
            field=models.CharField(default='#000000', max_length=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='league',
            name='icon',
            field=models.ImageField(upload_to='assets/leagues/icons'),
        ),
    ]
