# Generated by Django 4.2.3 on 2023-07-22 00:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_enrolled_users',
            field=models.ManyToManyField(blank=True, related_name='course_enrolled_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
