# Generated by Django 4.1 on 2023-09-04 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ('-updated_at', '-created_at')},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ('-updated_at', '-created_at')},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ('-updated_at', '-created_at')},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ('-created_at', '-updated_at')},
        ),
        migrations.AddField(
            model_name='topiccomment',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='topic_comment_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='topiccomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_comment_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
