# Generated by Django 4.2.6 on 2023-11-11 18:29

from django.db import migrations, models
import martor.models
import pathlib
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='description',
            field=models.TextField(blank=True, help_text='Lesson description (Optional)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='description',
            field=models.TextField(blank=True, help_text='Module description (Optional)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='description',
            field=models.TextField(blank=True, help_text='Topic description (Optional)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='illustration',
            field=models.ImageField(help_text='Course art cover perferly 512x512 size', upload_to=pathlib.PurePosixPath('assets/courses/backgrounds')),
        ),
        migrations.AlterField(
            model_name='course',
            name='is_visible',
            field=models.BooleanField(default=True, help_text='Is course visible to learners?'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(help_text='Course name', max_length=128),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='is_visible',
            field=models.BooleanField(default=True, help_text='Is lesson visible to learners?'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='name',
            field=models.CharField(help_text='Lesson name', max_length=60),
        ),
        migrations.AlterField(
            model_name='module',
            name='is_visible',
            field=models.BooleanField(default=True, help_text='Is module visible to learners?'),
        ),
        migrations.AlterField(
            model_name='module',
            name='name',
            field=models.CharField(help_text='Module name', max_length=60),
        ),
        migrations.AlterField(
            model_name='topic',
            name='content',
            field=martor.models.MartorField(blank=True, help_text='Topic content in markdown format', null=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='is_visible',
            field=models.BooleanField(default=True, help_text='Is topic visible to learners?'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='thread_reference',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='title',
            field=models.CharField(help_text='Topic title', max_length=128),
        ),
    ]
