# Generated by Django 4.1 on 2023-09-04 13:03

from django.db import migrations
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_alter_course_options_alter_lesson_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topiccomment',
            name='content',
            field=martor.models.MartorField(),
        ),
    ]
