# Generated by Django 4.2.8 on 2023-12-17 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_category_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='category',
            name='editors',
        ),
    ]
