# Generated by Django 4.2.5 on 2023-09-23 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_rename_completed_topicquestion_answered_users_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicquestion',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_questions', to='catalogue.topic'),
        ),
    ]
