# Generated by Django 4.2.6 on 2023-12-01 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0001_initial'),
        ('catalogue', '0003_category_description_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='tags',
            field=models.ManyToManyField(to='metadata.tag'),
        ),
    ]
