# Generated by Django 4.1 on 2023-09-04 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_alter_topiccomment_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='topiccomment',
            name='sub_topic_comment',
            field=models.ManyToManyField(blank=True, to='catalogue.topiccomment'),
        ),
    ]
