# Generated by Django 4.2.6 on 2023-12-04 11:40

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0004_course_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='illustration',
            field=models.FileField(help_text='Course art cover perferly 512x512 size', upload_to=pathlib.PurePosixPath('assets/courses/backgrounds')),
        ),
    ]
