# Generated by Django 4.1 on 2023-09-04 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0005_rename_sub_topic_comment_topiccomment_sub_topic_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='topiccomment',
            name='is_parent',
            field=models.BooleanField(default=False),
        ),
    ]
