# Generated by Django 4.2.5 on 2023-10-04 01:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalogue', '0005_alter_lesson_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
