# Generated by Django 4.2.5 on 2023-10-04 01:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalogue', '0006_alter_topic_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='catalogue.course'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='catalogue.lesson'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='topic_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
