# Generated by Django 4.1 on 2023-09-05 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0006_topiccomment_is_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topiccomment',
            name='content',
            field=models.TextField(),
        ),
    ]
