# Generated by Django 4.1 on 2023-09-05 03:52

from django.db import migrations
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0007_alter_topiccomment_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topiccomment',
            name='content',
            field=martor.models.MartorField(),
        ),
    ]
