# Generated by Django 4.2.6 on 2023-11-30 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reward', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='type',
            field=models.TextField(choices=[('REWARD_ACHIEVE', 'Reward achieved'), ('LESSON_COMPLETE', 'Lesson completed'), ('STREAK_COMPLETE', 'Streak completed'), ('LEAGUE_COMPLETE', 'League Completed')], max_length=128),
        ),
    ]
