# Generated by Django 4.2.5 on 2023-09-25 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reward', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='type',
            field=models.TextField(choices=[('ACHIEVER', 'Achiever'), ('HAT_TRICK', 'Hat Trick'), ('COURSE_MASTER', 'Course Master'), ('COURSE_NINJA', 'Course Ninja'), ('VERIFY_ACCOUNT', 'Verify Account'), ('NEW_CAREER_AWAITS', 'New Career Awaits'), ('WHERE_THE_MAGIC_HAPPENS', 'Where The Magic Happens'), ('JUST_GETTING_STARTED', 'Just Getting Started'), ('FEARLESS', 'Fearless'), ('ENGAGED_IN', 'Engaged In'), ('WE_ARE_IN_THIS_TOGETHER', 'We Are In This Together')], max_length=128, unique=True),
        ),
    ]
