# Generated by Django 4.2.3 on 2023-07-26 16:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reward', '0002_streak_date_streak_is_complete_streak_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='reward_unlocked_users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
