# Generated by Django 4.2.3 on 2023-07-27 23:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reward', '0003_reward_reward_unlocked_users'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='streak',
            name='User can only create one streak instance for a date',
        ),
        migrations.RemoveField(
            model_name='streak',
            name='is_complete',
        ),
        migrations.RemoveField(
            model_name='streak',
            name='user',
        ),
        migrations.AddField(
            model_name='streak',
            name='streak_complete_users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='streak',
            name='date',
            field=models.DateField(unique=True),
        ),
    ]
